In [1]:
import torch 
import numpy as np

In [6]:
x = torch.tensor([[1,2],[3,4]])

In [4]:
print(x)

tensor([[1, 2],
        [3, 4]])


In [13]:
print(x)

tensor([[0, 1],
        [2, 3]])


In [25]:
x = np.array([[2,1],[4,3]])
x

array([[2, 1],
       [4, 3]])

In [34]:
import matplotlib.pyplot as plt
X = np.array([3,1,2,5,4])
Y = np.array([1,5,2,9,1])
order = np.argsort(X)
Xs = np.array(X)[order]

In [44]:
x = np.array([1])
x

array([1])

In [46]:
x

array([1])